### ISSUE TITLE
Adding missing methods and statements in Helper class and FieldsContracts class

### ISSUE THREAD

**Issue by michelo243** [Akilimali003/Delicious-restaurant#6]
Ajouter les méthodes manquantes, les champs et les requêtes manquantes dans les classes **FieldsContracts.kt** et **DeliciousDatabaseHelper.kt** tout en respectant les nomenclatures utilisées dans _les webservices_.

**Comment by Akilimali003** [comment]
I don't know what to do with this one, git seems new for me sir!!! i need your help to manage this one and be able to clone the project....

**Comment by michelo243** [comment]
you have the SQL model for the app. here you have to see how i done things in the SQLiteHelper and do the same thing for all other tables. That's mean :
- create others tables
- updating FieldsContracts class
- testing inserting data using WebServices

**Comment by Akilimali003** [comment]
![Capture](https://user-images.githubusercontent.com/27545925/61566612-79a8f900-aa85-11e9-9b7a-514c4b4e8ceb.PNG)
 the problem i have by pulling the update you have done, they write this error message i don't know how to manage this one.

**Comment by Akilimali003** [comment]
ALready done thanks!

**Comment by michelo243** [comment]
All things works fine with minors bugs. so next step will be to correct those bugs
